### ISSUE TITLE
Enhancement: Add screen init functionality

### ISSUE THREAD

**Issue by jacwib** [Wolfvak/BootAnim9#10]
...So you can change the brightness!

That would be pretty useful, i can barely see my bootanimation when the room isnt dark.

**Comment by Wolfvak** [comment]
https://github.com/Wolfvak/BootAnim9/issues/11#issuecomment-246491408

**Comment by Wolfvak** [comment]
Fixed with https://github.com/Wolfvak/BootAnim9/commit/c683a8a8314c7ae0a46bbfb6b09a59e2edda5d6e
