### ISSUE TITLE
Boots straight into Luma3DS on a9lh New 3DS

### ISSUE THREAD

**Issue by SplatMan333** [Wolfvak/BootAnim9#16]
I copied all of the releases's files to the root of my SD Card, and placed my original a9lh payload in the anim folder, and renamed it arm9payload.bin. But my 3DS just boots straight into Luma CFW. Please help!

**Comment by Wolfvak** [comment]
I'd suppose you never placed any animations in the `anim` folder, therefore the chainloader kicked in inmediately.
