### ISSUE TITLE
Black Screen on boot (latest version used)

### ISSUE THREAD

**Issue by Zotackshinta** [Wolfvak/BootAnim9#17]
After doing everything
my N3dsXL just hangs on a black screen (due to the A9LH not being updated)
i use the latest A9LH from Luma3ds 6.6
SW version: 11.3.0.36-U +Luma3ds&A9LH
Luma version: 6.6
BootAnim9 version: 0.6.2

**Comment by Wolfvak** [comment]
You need to use a screen init a9lh... either get one that does it automatically or rename to `arm9loaderhax_si.bin`
