### ISSUE TITLE
New chainloader appears to break the application

### ISSUE THREAD

**Issue by Wolfvak** [Wolfvak/BootAnim9#4]
Alright, the chainloader is apparently not functioning correctly. Can anyone test what happens when you don't have an external payload?

In my case, the top screen turns white (intended behaviour, easier to diagnose)

**Comment by chaoskagami** [comment]
This is actually highly odd and I'm not sure what's going on here. I figured out precisely where it's crashing now - on the f_close calls in drawAnimation(). I have no clue why this is occuring. It may be safe to remove them since technically there's no real open handles and the 3DS clears the memory anyways.

The only variable here is that I updated my arm9bootloader.bin before it started.

**Comment by Wolfvak** [comment]
Well, try building a modified BootAnim9 without the f_close() and send it to Docmudkipz over PM for testing, he'll be active.

**Comment by chaoskagami** [comment]
I used tactical placements of clearScreen. I placed it before the f_close(), screen was black. After the f_close(), screen was the last animation frame. So I was clearing the screen as a sort of breakpoint.

**Comment by chaoskagami** [comment]
I'll build a copy and post it to the forums. Gimme a sec.

**Comment by Wolfvak** [comment]
You might wanna check this out then https://github.com/Wolfvak/A9LH_Homebrew_Template/blob/master/source/draw.c#L21

**Comment by chaoskagami** [comment]
Built a copy of master with the f_closes removed. Posted to forums. The only difference is commenting the f_closes.

**Comment by chaoskagami** [comment]
Looks @DrZepto can't test till tomorrow, but he has AuReiNand as the Plailect guide, so that rules out BootCtr9.

I honestly have no clue why removing the f_closes fixes it.

**Comment by Wolfvak** [comment]
Yeah, another beta tester I know can't do it now as well.
Let's just hope it fixes everything.
I'll just update the current file in the release with one including your fix.

**Comment by chaoskagami** [comment]
@Docmudkipz has confirmed that it functions with f_close removed.

Seriously, WTF.

**Comment by chaoskagami** [comment]
https://mega.nz/#!fZJEBRhK!cJpZ8UF6YwHZ0duZ1aNI0rBwFA6XgK3oRoGSYhU04_s

^ That's the build I did. Basically, comment out:
```
f_close(&bgr_anim_bottom);
f_close(&bgr_anim_top);
```

Still, I have no clue why that fixes this.

**Comment by Wolfvak** [comment]
Yeah, added you to the support conversation and it works apparently. I already updated Release v0.3.2 with this fix and already commited the changes to the main repo.

**Comment by chaoskagami** [comment]
I noticed.

Removing f_close is a strange fix though. Was fatfs updated in any of the commits?

**Comment by Wolfvak** [comment]
Not really. I'm using the fatfs from an old AuReiNAND commit, which in turn was modified from ReiNAND, which was modified from ctr by b1l1s. I might try to update FatFS' core without touching any of the 3DS specific files, see if that fixes it
