### ISSUE TITLE
Is it possible to "parallel-load" instead of "chain-load"?

### ISSUE THREAD

**Issue by liangziqi124** [Wolfvak/BootAnim9#6]
Is it possible to write the animation into memory, leave it to play but load the target payload at the same time?
As the loading of a payload could last 10 seconds, during which an opening animation could bring more fun. On the other hand, the chain-load would make the duration longer.

**Comment by docmudkipz** [comment]
IIRC BA9 used to load the animation into memory before putting it on the screen which had caused speed problems, as of current it loads straight into a framebuffer from the SD card. Besides, every payload out there loads in at max a couple of seconds. Loading the other payload while the animation is playing might cause some problems anyway(at least in my mind) on top of loading the animation into memory would take an extra bit of time and may cancel out any benefits of preloading the other payload.

**Comment by Wolfvak** [comment]
>As the loading of a payload could last 10 seconds

This is completely false. The one that takes up to 10 seconds to boot (not load) is the FIRM itself, which is loaded by Cakes, Luma, ReiNAND, etc.

Payloads themselves are loaded in miliseconds, that's why a9lh is described as "instantaneous".

Unfortunately, there's nothing I can do about it
