### ISSUE TITLE
the #Bricked4Ever code

### ISSUE THREAD

**Issue by ZeroGravity83** [Wolfvak/BootAnim9#9]
https://github.com/Wolfvak/BootAnim9/commit/180fa1eef08838aca12844e59fce1707664bb125
I see you don't like Gateway, but I gotta say you are going too far. Adding a code like this just to annoy its users is a terrible move. It's a shame that you resorted to malicious behavior.

**Comment by Wolfvak** [comment]
"It's a shame that you resorted to malicious behavior."

The irony is tangible.

https://gbatemp.net/threads/warning-gateway-team-bricks-card-on-purpose.360568/
https://gbatemp.net/threads/psa-gateway-is-making-more-bricks.404505/
http://wololo.net/2015/12/01/gateway3ds-bricking-consoles-if-you-use-a-competitors-product-again/
http://www.maxconsole.com/maxcon_forums/threads/279891-Gateway-3DS-Releases-Statement-about-RMA-ing-your-Bricks
http://wiiuhax.com/gateway-continues-to-brick-the-story-continues/

I'm just trying to make a point here, the code will be removed

**Comment by Wolfvak** [comment]
SOON™

**Comment by mariogamer2** [comment]
Malicious behavior.... LOL

**Comment by ZeroGravity83** [comment]
So what? Ironically you are doing the same thing as Gateway team when they implemented the so-called "brickcode" years ago, so you are no better than them -.-

**Comment by Wolfvak** [comment]
This is an actual issue that will be fixed

**Comment by Wolfvak** [comment]
Fixed with https://github.com/Wolfvak/BootAnim9/commit/3fe662d0648363f7947c54545ab11b284b4f4eb5
